[workspace]
members = [
    "djgpp",
    "dos_x",
    "examples/ferris",
    "examples/opl",
]

resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
strip = "debuginfo"
panic = "abort"
lto = "fat"
