[package]
name = "dos-rs"
version = "0.1.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.dev]
opt-level = 1

[profile.release]
strip = "debuginfo"
opt-level = "z"
