[package]
name = "ferris"
publish = false
description = "An example of a DOS program written in Rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
dos_x = { version = "0.1.0", path = "../../dos_x" }
libm = "0.2.8"
