name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true
        rustflags: "-W warnings"
      # cache elf2djgpp
    - name: Cache elf2djgpp
      id: cache-elf2djgpp
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/elf2djgpp
          ~/.cargo/bin/elf2djgpp-rev.txt
        key: ${{ runner.os }}-elf2djgpp
    - name: Cache djgpp-gcc
      id: cache-djgpp-gcc
      uses: actions/cache@v3
      with:
        path: /op/djgpp
        key: ${{ runner.os }}-i586-djgpp-gcc1220
    - uses: actions/checkout@v3
    - name: Download and install djgpp-gcc
      run: bash install_djgpp-gcc.sh
    - name: Build and install elf2djgpp
      run: bash install_elf2djgpp.sh && echo /opt/djgpp/bin >> $GITHUB_PATH
    - name: Build
      env:
        # binaries of msdosdjgpp-gcc are for i586
        CC: i586-pc-msdosdjgpp-gcc
        ARCH: i586
      run: ./build.sh
